// <auto-generated>
// 에디터에서 자동 생성되는 파일입니다. 수동으로 수정하지 마십시오.
// Trigger: ProjectSettings/TagManager.asset 변경 또는 Tools 메뉴
// </auto-generated>

namespace TBM.MaouSuika.Core
{
    public static class Layers
    {
        public const int DEFAULT = 0;
        public const int DEFAULT_MASK = 1 << 0;
        public const int TRANSPARENT_FX = 1;
        public const int TRANSPARENT_FX_MASK = 1 << 1;
        public const int IGNORE_RAYCAST = 2;
        public const int IGNORE_RAYCAST_MASK = 1 << 2;
        public const int WATER = 4;
        public const int WATER_MASK = 1 << 4;
        public const int UI = 5;
        public const int UI_MASK = 1 << 5;
        public const int SUIKA = 10;
        public const int SUIKA_MASK = 1 << 10;
        public const int WALL = 11;
        public const int WALL_MASK = 1 << 11;
        public const int BATTLE_SIDE_LEFT = 15;
        public const int BATTLE_SIDE_LEFT_MASK = 1 << 15;
        public const int BATTLE_SIDE_RIGHT = 16;
        public const int BATTLE_SIDE_RIGHT_MASK = 1 << 16;
    }
}
