// <auto-generated>
// 에디터에서 자동 생성되는 파일입니다. 수동으로 수정하지 마십시오.
// Trigger: ProjectSettings/TagManager.asset 변경 또는 Tools 메뉴
// </auto-generated>

namespace TBM.MaouSuika.Core
{
    public static class SortingLayers
    {
        public const int DEFAULT = 0;
        public const int BACKGROUND = 702573803;
        public const int FAR_GROUND = 1121060937;
        public const int FAR_GROUND_SHADOW = 419227431;
        public const int NEAR_GROUND = 1975171427;
        public const int NEAR_GROUND_SHADOW = 1893507941;
        public const int SHADOW = 438741943;
        public const int NEAR_BACKGROUND = -347605491;
        public const int OBJECT = -135992693;
        public const int OBJECT_FRONT = 922430477;
        public const int NEAR_FOREGROUND = -1949592627;
        public const int EFFECT = 2091037007;
        public const int UI = -784737413;
        public const int NEW_LAYER_11 = -1632967613;
    }
}
