// <auto-generated>
// 에디터에서 자동 생성되는 파일입니다. 수동으로 수정하지 마십시오.
// Trigger: ProjectSettings/TagManager.asset 변경 또는 Tools 메뉴
// </auto-generated>

namespace TBM.MaouSuika.Core
{
    public static class Tags
    {
        public const string UNTAGGED = "Untagged";
        public const string RESPAWN = "Respawn";
        public const string FINISH = "Finish";
        public const string EDITOR_ONLY = "EditorOnly";
        public const string MAIN_CAMERA = "MainCamera";
        public const string PLAYER = "Player";
        public const string GAME_CONTROLLER = "GameController";
        public const string GROUND = "Ground";
    }
}
