using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditorInternal;
using UnityEngine;

namespace TBM.MaouSuika.Core.Editor
{
    public class LayerConstantGenerator : AssetPostprocessor
    {
        private const string FILE_PATH = "Assets/_01_Scripts/Core/Common/";
        private const string NAMESPACE = "TBM.MaouSuika.Core";
        private const string MENU_PATH = "TBM/Maou Suika/Generate TagManager Constants";

// TagManager.asset 변경 감지
        private static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets,
            string[] movedAssets, string[] movedFromAssetPaths)
        {
            foreach (var asset in importedAssets)
            {
                if (asset.EndsWith("ProjectSettings/TagManager.asset"))
                {
                    GenerateAll();
                    break;
                }
            }
        }

        [MenuItem(MENU_PATH)]
        public static void GenerateAll()
        {
            if (!Directory.Exists(FILE_PATH))
            {
                Directory.CreateDirectory(FILE_PATH);
            }

            GenerateTags();
            GenerateLayers();
            GenerateSortingLayers();

            AssetDatabase.Refresh();
            Debug.Log($"[TagManagerGenerator] Tags, Layers, SortingLayers 파일이 독립적으로 생성되었습니다. 위치: {FILE_PATH}");
        }

        private static void GenerateTags()
        {
            var sb = new StringBuilder();
            sb.AppendLine("    public static class Tags");
            sb.AppendLine("    {");
            foreach (string tag in InternalEditorUtility.tags)
            {
                sb.AppendLine($"        public const string {FormatIdentifier(tag)} = \"{tag}\";");
            }

            sb.AppendLine("    }");

            WriteToFile("Tags.cs", sb.ToString());
        }

        private static void GenerateLayers()
        {
            var sb = new StringBuilder();
            sb.AppendLine("    public static class Layers");
            sb.AppendLine("    {");
            for (int i = 0; i < 32; i++)
            {
                string layerName = LayerMask.LayerToName(i);
                if (!string.IsNullOrEmpty(layerName))
                {
                    string safeName = FormatIdentifier(layerName);
                    sb.AppendLine($"        public const int {safeName} = {i};");
                    sb.AppendLine($"        public const int {safeName}_MASK = 1 << {i};");
                }
            }

            sb.AppendLine("    }");

            WriteToFile("Layers.cs", sb.ToString());
        }

        private static void GenerateSortingLayers()
        {
            var sb = new StringBuilder();
            sb.AppendLine("    public static class SortingLayers");
            sb.AppendLine("    {");
            foreach (var layer in SortingLayer.layers)
            {
                sb.AppendLine($"        public const int {FormatIdentifier(layer.name)} = {layer.id};");
            }

            sb.AppendLine("    }");

            WriteToFile("SortingLayers.cs", sb.ToString());
        }

        // 공통 파일 작성 로직
        private static void WriteToFile(string fileName, string classContent)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// 에디터에서 자동 생성되는 파일입니다. 수동으로 수정하지 마십시오.");
            sb.AppendLine("// Trigger: ProjectSettings/TagManager.asset 변경 또는 Tools 메뉴");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine($"namespace {NAMESPACE}");
            sb.AppendLine("{");
            sb.Append(classContent);
            sb.AppendLine("}");

            string fullPath = Path.Combine(FILE_PATH, fileName);
            File.WriteAllText(fullPath, sb.ToString(), Encoding.UTF8);
        }

// 식별자 포맷팅 (PascalCase -> UPPER_SNAKE_CASE)
        private static string FormatIdentifier(string name)
        {
            if (string.IsNullOrEmpty(name)) return string.Empty;

            // 1. 공백 및 특수문자를 언더바(_)로 치환
            string safeName = Regex.Replace(name, @"[^a-zA-Z0-9_]", "_");

            // 2. 소문자-대문자 경계에 언더바 삽입 (예: ObjectFront -> Object_Front)
            safeName = Regex.Replace(safeName, @"([a-z])([A-Z])", "$1_$2");

            // 3. 연속된 대문자 뒤에 소문자가 오는 경우 경계 처리 (예: UIFront -> UI_Front)
            safeName = Regex.Replace(safeName, @"([A-Z])([A-Z][a-z])", "$1_$2");

            // 4. 전체 대문자 변환
            safeName = safeName.ToUpperInvariant();

            // 5. 숫자로 시작하는 경우 C# 문법 오류 방지를 위해 앞에 언더바 추가
            if (char.IsDigit(safeName[0]))
            {
                safeName = "_" + safeName;
            }

            // 6. 중복된 언더바 정리 (예: __ -> _)
            safeName = Regex.Replace(safeName, @"_+", "_");

            // 7. 앞뒤 언더바 제거 (예: _OBJECT_FRONT_ -> OBJECT_FRONT)
            return safeName.Trim('_');
        }
    }
}